// hearthstone packet type
#define PTYPE_GET_GAME_STATE	1
#define PTYPE_CHOOSE_OPTION		2
#define PTYPE_CHOOSE_ENTITIES	3
#define PTYPE_PRE_CAST			4
#define PTYPE_DEBUG_MESSAGE		5
#define PTYPE_CLIENT_PACKET		6
#define PTYPE_START_GAME_STATE	7
#define PTYPE_FINISH_GAME_STATE	8
#define PTYPE_TURN_TIMER		9
#define PTYPE_NACK_OPTION		10
#define PTYPE_GIVE_UP			11
#define PTYPE_GAME_CANCELLED	12
#define PTYPE_ALL_OPTIONS		14
#define PTYPE_USER_UI			15
#define PTYPE_GAME_SETUP		16
#define PTYPE_ENTITY_CHOICE		17
#define PTYPE_PRE_LOAD			18
#define PTYPE_POWER_HISTORY		19
#define PTYPE_NOTIFICATION		21
#define PTYPE_AUTO_LOGIN		103
#define PTYPE_BEGIN_PLAYING		113
#define PTYPE_GAME_STARTING		114
#define PTYPE_DEBUG_CONSOLE_COMMAND		123
#define PTYPE_DEBUG_CONSOLE_RESPONSE	124
#define PTYPE_AURORA_HANDSHAKE	168

